/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCapitalRouteImport } from './routes/app.capital'
import { Route as AppGuideRouteImport } from './routes/app.guide'
import { Route as AppLegalPersonsRouteImport } from './routes/app.legal-persons'
import { Route as AppLimitsRouteImport } from './routes/app.limits'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPhysicalPersonsRouteImport } from './routes/app.physical-persons'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'
import { Route as AppAdminCodeListsRouteImport } from './routes/app.admin.code-lists'
import { Route as AppAdminPeriodRouteImport } from './routes/app.admin.period'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCapitalRoute = AppCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalPersonsRoute = AppLegalPersonsRouteImport.update({
  id: '/legal-persons',
  path: '/legal-persons',
  getParentRoute: () => AppRoute,
} as any)
const AppLimitsRoute = AppLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPhysicalPersonsRoute = AppPhysicalPersonsRouteImport.update({
  id: '/physical-persons',
  path: '/physical-persons',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCodeListsRoute = AppAdminCodeListsRouteImport.update({
  id: '/admin/code-lists',
  path: '/admin/code-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPeriodRoute = AppAdminPeriodRouteImport.update({
  id: '/admin/period',
  path: '/admin/period',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/capital': typeof AppCapitalRoute
  '/app/guide': typeof AppGuideRoute
  '/app/legal-persons': typeof AppLegalPersonsRoute
  '/app/limits': typeof AppLimitsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/physical-persons': typeof AppPhysicalPersonsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/code-lists': typeof AppAdminCodeListsRoute
  '/app/admin/period': typeof AppAdminPeriodRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/capital': typeof AppCapitalRoute
  '/app/guide': typeof AppGuideRoute
  '/app/legal-persons': typeof AppLegalPersonsRoute
  '/app/limits': typeof AppLimitsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/physical-persons': typeof AppPhysicalPersonsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/code-lists': typeof AppAdminCodeListsRoute
  '/app/admin/period': typeof AppAdminPeriodRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/capital': typeof AppCapitalRoute
  '/app/guide': typeof AppGuideRoute
  '/app/legal-persons': typeof AppLegalPersonsRoute
  '/app/limits': typeof AppLimitsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/physical-persons': typeof AppPhysicalPersonsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/code-lists': typeof AppAdminCodeListsRoute
  '/app/admin/period': typeof AppAdminPeriodRoute
  '/app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/capital'
    | '/app/guide'
    | '/app/legal-persons'
    | '/app/limits'
    | '/app/notifications'
    | '/app/physical-persons'
    | '/app/profile'
    | '/app/reports'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/code-lists'
    | '/app/admin/period'
    | '/app/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/capital'
    | '/app/guide'
    | '/app/legal-persons'
    | '/app/limits'
    | '/app/notifications'
    | '/app/physical-persons'
    | '/app/profile'
    | '/app/reports'
    | '/app'
    | '/app/capital'
    | '/app/admin/audit'
    | '/app/admin/code-lists'
    | '/app/admin/period'
    | '/app/admin/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/capital'
    | '/app/guide'
    | '/app/legal-persons'
    | '/app/limits'
    | '/app/notifications'
    | '/app/physical-persons'
    | '/app/profile'
    | '/app/reports'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/code-lists'
    | '/app/admin/period'
    | '/app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/capital': {
      id: '/app/capital'
      path: '/capital'
      fullPath: '/app/capital'
      preLoaderRoute: typeof AppCapitalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guide': {
      id: '/app/guide'
      path: '/guide'
      fullPath: '/app/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/legal-persons': {
      id: '/app/legal-persons'
      path: '/legal-persons'
      fullPath: '/app/legal-persons'
      preLoaderRoute: typeof AppLegalPersonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/limits': {
      id: '/app/limits'
      path: '/limits'
      fullPath: '/app/limits'
      preLoaderRoute: typeof AppLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/physical-persons': {
      id: '/app/physical-persons'
      path: '/physical-persons'
      fullPath: '/app/physical-persons'
      preLoaderRoute: typeof AppPhysicalPersonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/code-lists': {
      id: '/app/admin/code-lists'
      path: '/admin/code-lists'
      fullPath: '/app/admin/code-lists'
      preLoaderRoute: typeof AppAdminCodeListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/period': {
      id: '/app/admin/period'
      path: '/admin/period'
      fullPath: '/app/admin/period'
      preLoaderRoute: typeof AppAdminPeriodRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCapitalRoute: typeof AppCapitalRoute
  AppGuideRoute: typeof AppGuideRoute
  AppLegalPersonsRoute: typeof AppLegalPersonsRoute
  AppLimitsRoute: typeof AppLimitsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPhysicalPersonsRoute: typeof AppPhysicalPersonsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCodeListsRoute: typeof AppAdminCodeListsRoute
  AppAdminPeriodRoute: typeof AppAdminPeriodRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCapitalRoute: AppCapitalRoute,
  AppGuideRoute: AppGuideRoute,
  AppLegalPersonsRoute: AppLegalPersonsRoute,
  AppLimitsRoute: AppLimitsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPhysicalPersonsRoute: AppPhysicalPersonsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCodeListsRoute: AppAdminCodeListsRoute,
  AppAdminPeriodRoute: AppAdminPeriodRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
