/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppResourceRouteImport } from './routes/app.$resource'
import { Route as AppAppraisersRouteImport } from './routes/app.appraisers'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppBranchesRouteImport } from './routes/app.branches'
import { Route as AppCodeListsRouteImport } from './routes/app.code-lists'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppHealthRouteImport } from './routes/app.health'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppProtocolRouteImport } from './routes/app.protocol'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppResourceRoute = AppResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => AppRoute,
} as any)
const AppAppraisersRoute = AppAppraisersRouteImport.update({
  id: '/appraisers',
  path: '/appraisers',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesRoute = AppBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeListsRoute = AppCodeListsRouteImport.update({
  id: '/code-lists',
  path: '/code-lists',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthRoute = AppHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProtocolRoute = AppProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$resource': typeof AppResourceRoute
  '/app/appraisers': typeof AppAppraisersRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/code-lists': typeof AppCodeListsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/health': typeof AppHealthRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/protocol': typeof AppProtocolRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$resource': typeof AppResourceRoute
  '/app/appraisers': typeof AppAppraisersRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/code-lists': typeof AppCodeListsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/health': typeof AppHealthRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/protocol': typeof AppProtocolRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/$resource': typeof AppResourceRoute
  '/app/appraisers': typeof AppAppraisersRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branches': typeof AppBranchesRoute
  '/app/code-lists': typeof AppCodeListsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/health': typeof AppHealthRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/protocol': typeof AppProtocolRoute
  '/app/reports': typeof AppReportsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/orders_/$id': typeof AppOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/$resource'
    | '/app/appraisers'
    | '/app/audit'
    | '/app/branches'
    | '/app/code-lists'
    | '/app/documents'
    | '/app/health'
    | '/app/notifications'
    | '/app/orders'
    | '/app/protocol'
    | '/app/reports'
    | '/app/roles'
    | '/app/tasks'
    | '/app/users'
    | '/app/'
    | '/app/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$resource'
    | '/app/appraisers'
    | '/app/audit'
    | '/app/branches'
    | '/app/code-lists'
    | '/app/documents'
    | '/app/health'
    | '/app/notifications'
    | '/app/orders'
    | '/app/protocol'
    | '/app/reports'
    | '/app/roles'
    | '/app/tasks'
    | '/app/users'
    | '/app'
    | '/app/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/$resource'
    | '/app/appraisers'
    | '/app/audit'
    | '/app/branches'
    | '/app/code-lists'
    | '/app/documents'
    | '/app/health'
    | '/app/notifications'
    | '/app/orders'
    | '/app/protocol'
    | '/app/reports'
    | '/app/roles'
    | '/app/tasks'
    | '/app/users'
    | '/app/'
    | '/app/orders_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$resource': {
      id: '/app/$resource'
      path: '/$resource'
      fullPath: '/app/$resource'
      preLoaderRoute: typeof AppResourceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appraisers': {
      id: '/app/appraisers'
      path: '/appraisers'
      fullPath: '/app/appraisers'
      preLoaderRoute: typeof AppAppraisersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branches': {
      id: '/app/branches'
      path: '/branches'
      fullPath: '/app/branches'
      preLoaderRoute: typeof AppBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/code-lists': {
      id: '/app/code-lists'
      path: '/code-lists'
      fullPath: '/app/code-lists'
      preLoaderRoute: typeof AppCodeListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/health': {
      id: '/app/health'
      path: '/health'
      fullPath: '/app/health'
      preLoaderRoute: typeof AppHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/protocol': {
      id: '/app/protocol'
      path: '/protocol'
      fullPath: '/app/protocol'
      preLoaderRoute: typeof AppProtocolRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders_/$id': {
      id: '/app/orders_/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppResourceRoute: typeof AppResourceRoute
  AppAppraisersRoute: typeof AppAppraisersRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBranchesRoute: typeof AppBranchesRoute
  AppCodeListsRoute: typeof AppCodeListsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppHealthRoute: typeof AppHealthRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProtocolRoute: typeof AppProtocolRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppTasksRoute: typeof AppTasksRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppResourceRoute: AppResourceRoute,
  AppAppraisersRoute: AppAppraisersRoute,
  AppAuditRoute: AppAuditRoute,
  AppBranchesRoute: AppBranchesRoute,
  AppCodeListsRoute: AppCodeListsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppHealthRoute: AppHealthRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProtocolRoute: AppProtocolRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppTasksRoute: AppTasksRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
