import express from "express";
        import { authMiddleware } from "./middleware/auth";
        import { auditMiddleware } from "./middleware/audit";
        import { productRouter } from "./modules/products/products.routes";
import { orderRouter } from "./modules/orders/orders.routes";
        export const app = express();
        app.use(express.json());
        app.use("/products", auditMiddleware, authMiddleware, productRouter);
app.use("/orders", auditMiddleware, authMiddleware, orderRouter);
        app.get("/health", (_req, res) => res.status(200).json({ status: "ok" }));
