import express from "express";
        import { authMiddleware } from "./middleware/auth";
        import { auditMiddleware } from "./middleware/audit";
        import { ticketRouter } from "./modules/tickets/tickets.routes";
import { commentRouter } from "./modules/comments/comments.routes";
        export const app = express();
        app.use(express.json());
        app.use("/tickets", auditMiddleware, authMiddleware, ticketRouter);
app.use("/comments", auditMiddleware, authMiddleware, commentRouter);
        app.get("/health", (_req, res) => res.status(200).json({ status: "ok" }));
