// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RBBH.CollateralAppraisal.Infrastructure.Persistence;

#nullable disable

namespace RBBH.CollateralAppraisal.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828110219_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Appraisers.Appraiser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<int>("ClientScope")
                        .HasColumnType("int")
                        .HasColumnName("client_scope");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlacklisted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blacklisted");

                    b.Property<bool>("IsOnLeave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_on_leave");

                    b.Property<int>("LegalForm")
                        .HasColumnType("int")
                        .HasColumnName("legal_form");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("SupportedCities")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("supported_cities");

                    b.Property<string>("SupportedPropertyTypes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("supported_property_types");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsBlacklisted");

                    b.HasIndex("IsOnLeave");

                    b.ToTable("appraisers", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Audit.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActiveRole")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ActorFullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EntityDisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExternalRequestId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalResponseStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IntegrationDirection")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SourceConnectionName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceDatabase")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceSchema")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceTable")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("ActiveRole")
                        .HasDatabaseName("ix_audit_logs_active_role");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_audit_logs_module");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_audit_logs_severity");

                    b.HasIndex("SourceSystem")
                        .HasDatabaseName("ix_audit_logs_source_system");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_audit_logs_status");

                    b.HasIndex("TimestampUtc")
                        .HasDatabaseName("ix_audit_logs_timestamp_utc");

                    b.HasIndex("EntityType", "EntityKey")
                        .HasDatabaseName("ix_audit_logs_entity_type_key");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Branches.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("address");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_branches_city_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uix_branches_code");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Branches.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uix_cities_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Codebooks.Codebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_codebooks_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uix_codebooks_code_active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_codebooks_is_active");

                    b.ToTable("codebooks", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Codebooks.CodebookValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodebookKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodebookKey")
                        .HasDatabaseName("ix_codebook_values_key");

                    b.HasIndex("CodebookKey", "Code")
                        .IsUnique()
                        .HasDatabaseName("uix_codebook_values_key_code_active")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.HasIndex("CodebookKey", "IsActive")
                        .HasDatabaseName("ix_codebook_values_key_active");

                    b.ToTable("codebook_values", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Documents.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppraisalOrderId")
                        .HasColumnType("int")
                        .HasColumnName("appraisal_order_id");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("change_reason");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeactivatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("deactivated_by_user_id");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("deactivation_reason");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("original_file_name");

                    b.Property<int?>("PreviousVersionId")
                        .HasColumnType("int")
                        .HasColumnName("previous_version_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalOrderId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PreviousVersionId");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Documents.DocumentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedRoles")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("allowed_roles");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("document_templates", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Documents.SharedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeactivatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("deactivated_by_user_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.ToTable("shared_documents", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<string>("RecipientRole")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("recipient_role");

                    b.Property<string>("RecipientUserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("RelatedEntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("related_entity_type");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("Status");

                    b.HasIndex("RecipientUserId", "IsRead");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.AppraisalOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("accepted_at");

                    b.Property<string>("AcceptedByCAName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("accepted_by_ca_name");

                    b.Property<string>("AcceptedByCAUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("accepted_by_ca_user_id");

                    b.Property<string>("AmRecipientName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("am_recipient_name");

                    b.Property<DateTime?>("AppraisalDeliveredToCoAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("appraisal_delivered_to_co_at");

                    b.Property<decimal?>("AppraisalFee")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("appraisal_fee");

                    b.Property<int?>("AppraiserId")
                        .HasColumnType("int")
                        .HasColumnName("appraiser_id");

                    b.Property<int?>("AppraiserRating")
                        .HasColumnType("int")
                        .HasColumnName("appraiser_rating");

                    b.Property<int>("AppraiserReminderCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("appraiser_reminder_count");

                    b.Property<DateTime?>("AppraiserReminderLastSentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("appraiser_reminder_last_sent_at");

                    b.Property<DateTime?>("AppraiserVisitDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("appraiser_visit_date");

                    b.Property<string>("Branch")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("branch");

                    b.Property<string>("BranchAddress")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("branch_address");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("branch_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("ClientIdentifier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("client_identifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("client_name");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("client_type");

                    b.Property<DateTime?>("CoApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("co_approved_at");

                    b.Property<string>("CoApprovedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("co_approved_by_user_id");

                    b.Property<DateTime?>("CoDocumentationReviewStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("co_documentation_review_started_at");

                    b.Property<DateTime?>("CoOpinionSentToAmAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("co_opinion_sent_to_am_at");

                    b.Property<string>("CollateralStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("collateral_status");

                    b.Property<int?>("CollateralTypeId")
                        .HasColumnType("int")
                        .HasColumnName("collateral_type_id");

                    b.Property<int?>("CombinedCollateralTypeId")
                        .HasColumnType("int")
                        .HasColumnName("combined_collateral_type_id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime?>("CorrectedAppraisalReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("corrected_appraisal_received_at");

                    b.Property<int>("CorrectionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("correction_count");

                    b.Property<DateTime?>("CorrectionRequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("correction_requested_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("created_by_email");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by_role");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("DeliveryContactName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("delivery_contact_name");

                    b.Property<string>("DocumentationReviewStatus")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("documentation_review_status");

                    b.Property<DateTime?>("DocumentationSupplementAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("documentation_supplement_at");

                    b.Property<string>("EsgCertificate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("esg_certificate");

                    b.Property<int?>("FinalAppraisalDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("final_appraisal_document_id");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("internal_note");

                    b.Property<int?>("InvoiceDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_document_id");

                    b.Property<DateTime?>("InvoicePaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_paid_at");

                    b.Property<string>("InvoicePaidByName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("invoice_paid_by_name");

                    b.Property<string>("InvoicePaidByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invoice_paid_by_user_id");

                    b.Property<DateTime?>("InvoiceReceivedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_received_date");

                    b.Property<DateTime?>("InvoiceSentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_sent_date");

                    b.Property<DateTime?>("InvoiceSentForPaymentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_sent_for_payment_at");

                    b.Property<string>("InvoiceSentForPaymentByName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("invoice_sent_for_payment_by_name");

                    b.Property<string>("InvoiceSentForPaymentByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invoice_sent_for_payment_by_user_id");

                    b.Property<int>("InvoiceStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("invoice_status");

                    b.Property<DateTime?>("InvoiceUploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("invoice_uploaded_at");

                    b.Property<string>("InvoiceUploadedByName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("invoice_uploaded_by_name");

                    b.Property<string>("InvoiceUploadedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invoice_uploaded_by_user_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("OpinionsCompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("opinions_completed_at");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("order_number");

                    b.Property<DateTime?>("OrderSentToAppraiserAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("order_sent_to_appraiser_at");

                    b.Property<DateTime?>("OriginalReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("original_received_at");

                    b.Property<string>("OriginalReceivedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("original_received_by_user_id");

                    b.Property<string>("PaymentConsentStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_consent_status");

                    b.Property<string>("PropertyAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("property_address");

                    b.Property<string>("PropertyCity")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("property_city");

                    b.Property<DateTime?>("ReadyForProcedureAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ready_for_procedure_at");

                    b.Property<DateTime?>("RequestReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_received_at");

                    b.Property<DateTime?>("RequestSentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_sent_at");

                    b.Property<bool>("SalesConsentSigned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SalesConsentSignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesConsentSignedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignedDocumentsReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("signed_documents_received_at");

                    b.Property<decimal?>("SquareMetersCommercial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("square_meters_commercial");

                    b.Property<decimal?>("SquareMetersResidential")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("square_meters_residential");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WorkflowType")
                        .HasColumnType("int")
                        .HasColumnName("workflow_type");

                    b.HasKey("Id");

                    b.HasIndex("AppraiserId");

                    b.HasIndex("City");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_orders_created_at");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("AppraiserId", "Status");

                    b.HasIndex("CreatedByUserId", "IsDeleted")
                        .HasDatabaseName("ix_orders_owner_deleted");

                    b.HasIndex("CreatedByUserId", "Status")
                        .HasDatabaseName("ix_orders_owner_status");

                    b.HasIndex("Status", "City");

                    b.ToTable("appraisal_orders", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppraisalOrderId")
                        .HasColumnType("int")
                        .HasColumnName("appraisal_order_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("imported_at");

                    b.Property<string>("ImportedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("imported_by_user_id");

                    b.Property<int>("OpinionType")
                        .HasColumnType("int")
                        .HasColumnName("opinion_type");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalOrderId");

                    b.HasIndex("AppraisalOrderId", "OpinionType")
                        .IsUnique();

                    b.ToTable("order_opinions", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.OrderDeclinedAppraiser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppraisalOrderId")
                        .HasColumnType("int")
                        .HasColumnName("appraisal_order_id");

                    b.Property<int>("AppraiserId")
                        .HasColumnType("int")
                        .HasColumnName("appraiser_id");

                    b.Property<DateTime>("DeclinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("declined_at");

                    b.Property<string>("FreeText")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("free_text");

                    b.Property<bool>("IsTimeout")
                        .HasColumnType("bit")
                        .HasColumnName("is_timeout");

                    b.Property<int>("Reason")
                        .HasColumnType("int")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalOrderId")
                        .HasDatabaseName("ix_order_declined_appraisers_order_id");

                    b.HasIndex("AppraisalOrderId", "AppraiserId")
                        .HasDatabaseName("ix_order_declined_appraisers_order_appraiser");

                    b.ToTable("order_declined_appraisers", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.OrderProtocolEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at");

                    b.Property<string>("GeneratedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("generated_by_user_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("protocol_number");

                    b.Property<int>("ProtocolSequence")
                        .HasColumnType("int")
                        .HasColumnName("protocol_sequence");

                    b.Property<int>("ProtocolYear")
                        .HasColumnType("int")
                        .HasColumnName("protocol_year");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("ProtocolNumber")
                        .IsUnique();

                    b.HasIndex("ProtocolYear");

                    b.HasIndex("ProtocolYear", "ProtocolSequence")
                        .IsUnique();

                    b.ToTable("order_protocol_entries", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.QuoteRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppraisalOrderId")
                        .HasColumnType("int")
                        .HasColumnName("appraisal_order_id");

                    b.Property<int>("AppraiserId")
                        .HasColumnType("int")
                        .HasColumnName("appraiser_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("deadline");

                    b.Property<int?>("OfferedDays")
                        .HasColumnType("int")
                        .HasColumnName("offered_days");

                    b.Property<decimal?>("OfferedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("offered_price");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("SentByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sent_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("ThankYouSentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("thank_you_sent_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalOrderId");

                    b.HasIndex("AppraisalOrderId", "AppraiserId")
                        .IsUnique();

                    b.ToTable("quote_requests", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("accepted_at");

                    b.Property<string>("AcceptedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<int>("AppraisalOrderId")
                        .HasColumnType("int")
                        .HasColumnName("appraisal_order_id");

                    b.Property<string>("AssignedRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("assigned_role");

                    b.Property<string>("AssignedUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("completed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("TaskType")
                        .HasColumnType("int")
                        .HasColumnName("task_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppraisalOrderId");

                    b.HasIndex("AssignedRole");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("Status");

                    b.ToTable("task_items", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Roles.PermissionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("module");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Module");

                    b.ToTable("permission_definitions", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Roles.RoleDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsSystem");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("role_definitions", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Roles.RolePermission", b =>
                {
                    b.Property<int>("RoleDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("role_definition_id");

                    b.Property<int>("PermissionDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_definition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("created_by_user_id");

                    b.HasKey("RoleDefinitionId", "PermissionDefinitionId");

                    b.HasIndex("PermissionDefinitionId");

                    b.HasIndex("RoleDefinitionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Infrastructure.Audit.AuditOutboxEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "CreatedAt")
                        .HasDatabaseName("IX_AuditOutbox_Unprocessed")
                        .HasFilter("[ProcessedAt] IS NULL");

                    b.ToTable("AuditOutbox", (string)null);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Branches.Branch", b =>
                {
                    b.HasOne("RBBH.CollateralAppraisal.Domain.Branches.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.AppraisalOrder", b =>
                {
                    b.HasOne("RBBH.CollateralAppraisal.Domain.Appraisers.Appraiser", null)
                        .WithMany()
                        .HasForeignKey("AppraiserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.OrderProtocolEntry", b =>
                {
                    b.HasOne("RBBH.CollateralAppraisal.Domain.Orders.AppraisalOrder", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Orders.TaskItem", b =>
                {
                    b.HasOne("RBBH.CollateralAppraisal.Domain.Orders.AppraisalOrder", "AppraisalOrder")
                        .WithMany()
                        .HasForeignKey("AppraisalOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppraisalOrder");
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Roles.RolePermission", b =>
                {
                    b.HasOne("RBBH.CollateralAppraisal.Domain.Roles.PermissionDefinition", "PermissionDefinition")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RBBH.CollateralAppraisal.Domain.Roles.RoleDefinition", "RoleDefinition")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionDefinition");

                    b.Navigation("RoleDefinition");
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Roles.PermissionDefinition", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("RBBH.CollateralAppraisal.Domain.Roles.RoleDefinition", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
