import express from "express";
        import { authMiddleware } from "./middleware/auth";
        import { auditMiddleware } from "./middleware/audit";
        import { bookRouter } from "./modules/books/books.routes";
import { loanRouter } from "./modules/loans/loans.routes";
        export const app = express();
        app.use(express.json());
        app.use("/books", auditMiddleware, authMiddleware, bookRouter);
app.use("/loans", auditMiddleware, authMiddleware, loanRouter);
        app.get("/health", (_req, res) => res.status(200).json({ status: "ok" }));
