import express from "express";
        import { authMiddleware } from "./middleware/auth";
        import { auditMiddleware } from "./middleware/audit";
        import { invoiceRouter } from "./modules/invoices/invoices.routes";
import { paymentRouter } from "./modules/payments/payments.routes";
        export const app = express();
        app.use(express.json());
        app.use("/invoices", auditMiddleware, authMiddleware, invoiceRouter);
app.use("/payments", auditMiddleware, authMiddleware, paymentRouter);
        app.get("/health", (_req, res) => res.status(200).json({ status: "ok" }));
